MOUSEKEY_ENABLE = yes
EXTRAKEY_ENABLE = yes
CONSOLE_ENABLE = no
ENCODER_ENABLE = yes
LTO_ENABLE = yes
OLED_ENABLE = yes
NKRO_ENABLE = yes
ENCODER_MAP_ENABLE = yes
COMBO_ENABLE = no

BACKLIGHT_ENABLE = no
RGBLIGHT_ENABLE = no
RGB_MATRIX_ENABLE = yes

BOOTLOADER = atmel-dfu
